### ISSUE TITLE
%moneyNeeded% Not Found

### ISSUE THREAD

**Issue by kc9ryt** [games647/ScoreboardStats#100]
I have MCPrison Installed and when i try to add the money needed into the scoreboard i get the error message "Cannot find variable with name: (VariableItem{textVariable=false, variable=rank, displayText=§9Money Needed, score=0}) Maybe you misspelled it or the replacer isnt available yet".

**Comment by games647** [comment]
Do you have Vault installed?

**Comment by kc9ryt** [comment]
Yes I do

**Comment by games647** [comment]
You used the variable rank instead of moneyNeeded

**Comment by kc9ryt** [comment]
Here is what my code looks like. Is this not right?

# Main configuration

# Compatible mode for other plugins like HealthBar, ColoredTags, GhostPlayer, McCombatLevel, etc. ......
# or the vanilla scoreboard
# In case you miss the log message: this option requires the plugin called ProtocolLib
# This option will work around the Bukkit API and will send raw packets
compatibilityMode: true

# Should be the node disabled-worlds handled as whitelist or blacklist
disabled-worlds-whitelist: false

disabled-worlds:

Scoreboard:
  Title: '&a&lYour Stats'
  # seconds
  # For instant updates you can or 1 and it will update every second
  Update-delay: 2
  Items:
    # The Title must have under 48 characters
    # Title: Type
    '&9Online': '%online%'
    '&9Money': '%money%'
    '&9test': '%moneyNeeded%'

# Let ScoreboardStats track stats (kills, deaths, mobkills, killstreak) You need no plugin for this
enable-pvpstats: true

Temp-Scoreboard-enabled: true

Temp-Scoreboard:
  Title: '&a&lTop Kills'
  # %mob% | %kills% | %killstreak%
  Type: '%kills%'
  Color: '&9'
  # How many Players would be displayed
  Items: 5
  Intervall-show: 300
  Intervall-disappear: 300

pluginUpdate: true

**Comment by games647** [comment]
Which version do you have?

**Comment by games647** [comment]
Could you show me pic of the /pl output

**Comment by kc9ryt** [comment]
![screen shot 2016-06-18 at 10 38 35 am](https://cloud.githubusercontent.com/assets/3506952/16171601/fa0b9796-3540-11e6-84e9-b48b04ea3e03.png)
![screen shot 2016-06-18 at 10 39 15 am](https://cloud.githubusercontent.com/assets/3506952/16171600/fa09da32-3540-11e6-8d89-24031c0df25e.png)

**Comment by games647** [comment]
Which version of ScoreboardStats do you use?
