### ISSUE TITLE
Trouble with featherboard

### ISSUE THREAD

**Issue by Eichelberger6** [games647/ScoreboardStats#101]
I am working on a server, and wanted to use _featherboard_ as one of my plugins, but I can't get it to activate!  When i **/pl** and my plugins show up _featherboard_ is **red** and **inactive**.  How can I activae it?

**Comment by games647** [comment]
Use the support of Featherboard and not this plugin.

**Comment by Eichelberger6** [comment]
??

**Comment by games647** [comment]
This is for the plug in Scoreboardstats not for Featherboard.

**Comment by Eichelberger6** [comment]
but featherboard is what is supposed to work

**Comment by games647** [comment]
Use the support of FeatherBoard. This is a different plugin.

**Comment by Eichelberger6** [comment]
ohh sorry could you give me a link to the right one

**Comment by games647** [comment]
http://mvdwsoftware.freshdesk.com/

**Comment by Eichelberger6** [comment]
there is nothing on that site...

**Comment by games647** [comment]
>New support ticket
