### ISSUE TITLE
Scoreboardstats config order is messed up?

### ISSUE THREAD

**Issue by Alphatrooper** [games647/ScoreboardStats#104]
Okay so, I have my scoreboardstats config set up so it should display Ping, then Online players, then faction power, Exactly like this, config below.

Scoreboard:
  Title: '&c&lStats'
  # seconds
  # For instant updates you can or 1 and it will update every second
  Update-delay: 1
  Items:
    # The Title must have under 48 characters
    # Title: Type
    '&f&lPing Â»': '%ping%'
    '&f&lOnline Â»': '%online%'
    'F Power': '%power%'

but in-game it gets sorted as "Ping, F power, Online"? Can anyone help me?

https://gyazo.com/f3eaaed7e81f38e81481ce02640a41a0

**Comment by games647** [comment]
It's minecraft behavior, because it's used to be a leaderboard. Therefore the highest number is a the top.
