### ISSUE TITLE
Add an option in sql.yml to choose different MySQL table

### ISSUE THREAD

**Issue by KatsuroKurosaki** [games647/ScoreboardStats#106]
The title says all,
I would like an option to be added in the SQL config in order to have different MySQL tables, so that, I can run different stats on my BungeeCord network,

Thanks in advance

**Comment by games647** [comment]
What do you think about a configurable prefix?

**Comment by KatsuroKurosaki** [comment]
I know the table name in MySQL is: player_stats
Do you mean a new config option (Tableprefix) in sql.yml like this:
`SQL-Settings:`
`  Tableprefix: 'prefix_'`
`  Username: awesome_user`
`  Password: awesome_password`
`  Isolation: SERIALIZABLE`
`  Driver: com.mysql.jdbc.Driver`
`  Url: jdbc:mysql://localhost:3306/awesome_database`
`  Timeout: 1000`
`uuidUse: true`

The new table name will be: prefix_player_stats, and this value, by default, an empty string.
If so: All of my YES! :D
