### ISSUE TITLE
Adding , in numbers

### ISSUE THREAD

**Issue by Broanater** [games647/ScoreboardStats#109]
hello, I was wondering if there is a way I can make it so that for a balanace as an example the money on the side would show up as 10,000 instead of 10000. I just find that it makes things easier to understand at a quick glace to the scoreboard.

-Thanks

**Comment by games647** [comment]
That's impossible. Minecraft only allows 

Title (max 16. characters)
Text (max. 48 characters) | integer number (−2.147.483.648 up to 2.147.483.647	)
Text (max. 48 characters) | integer number (−2.147.483.648 up to 2.147.483.647	)
Text (max. 48 characters) | integer number (−2.147.483.648 up to 2.147.483.647	)
.... (-> 15 rows)
