### ISSUE TITLE
Dissapear ScoreBoardStats after relog

### ISSUE THREAD

**Issue by RostislavCBC** [games647/ScoreboardStats#112]
When I reload a server and login the server, ScoreBoardStats works, but when I relogin, ScoreBoardStats dissapears. If I try login the server with another version of Minecraft or login after some minutes\hours of my being away of the game, ScoreBoardStats doesn`t work. I need to reload the server to make ScoreBoardStats works again, but if I relogin, it dissapears again. I need set "compatibilityMode: false" to make it works after relogin, but another plugins don`t work if I set it. How can I fix it?
Sorry for my English.

Version: spigot 1.7.10
No error in console
Plugin list: AuthMe AutoMessage ChatGuard ChatManager ChestCommands ClearLag ClearWorld ColoredTags CustomJoinItems Essentials HealthBar Marriage MineResetLite MultiMOTD NoCheatPlus PermissionsEx PluginMetrics ScoreboardStats SmokeTrail Updater UralClans Vault WGFix WorldBorder WorldEdit WorldGuard iConomy mcjobs update

**Comment by games647** [comment]
ScoreboardStats conflicts with ColoredTags. You **have to activate** compatibility and install ProtocolLib.

**Comment by RostislavCBC** [comment]
I have had this plugin, but i haven`t mentioned about it.

**Comment by games647** [comment]
So you already have this plugin installed?

**Comment by RostislavCBC** [comment]
Yes I have

**Comment by games647** [comment]
Then activate compatibilityMode in ScoreboardStats. You wrote that you deactivated it.

**Comment by RostislavCBC** [comment]
When I activate it, ScoreBoardStats dissapears after relogin

**Comment by games647** [comment]
Could you post your log please.

**Comment by RostislavCBC** [comment]
09.08 17:59:49 [Multicraft] Loading server properties
09.08 17:59:49 [Multicraft] Starting server!
09.08 17:59:49 [Multicraft] Loaded config for "Spigot [1.7.9 - 1.7.10]"
09.08 17:59:49 [Multicraft] Updating eula.txt file
09.08 17:59:49 [Server] INFO Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
09.08 17:59:49 [Server] INFO This Spigot build supports Minecraft clients both of versions 1.7.x and of 1.8.x.
09.08 17:59:49 [Server] INFO *** It is imperative that backups be taken before running this build on your server! ***
09.08 17:59:49 [Server] INFO Please report any such issues to http://www.spigotmc.org/, stating your client, server, and if applicable BungeeCord versions.
09.08 17:59:49 [Server] INFO *** Any bug reports not running the very latest versions of these softwares will be ignored ***
09.08 17:59:54 [Server] INFO Starting minecraft server version 1.7.10
09.08 17:59:54 [Server] WARN To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
09.08 17:59:54 [Server] INFO Loading properties
09.08 17:59:54 [Server] INFO Default game type: SURVIVAL
09.08 17:59:54 [Server] INFO This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
09.08 17:59:54 [Server] INFO Server Ping Player Sample Count: 12
09.08 17:59:54 [Server] INFO Using 4 threads for Netty based IO
09.08 17:59:54 [Server] INFO Debug logging is disabled
09.08 17:59:54 [Server] INFO Generating keypair
09.08 17:59:54 [Server] INFO Starting Minecraft server on s2.craftbuy.ru:30627
09.08 17:59:54 [Server] INFO Set PluginClassLoader as parallel capable
09.08 17:59:55 [Server] INFO [INFO][NoCheatPlus] Tue Aug 09 17:59:55 MSK 2016
09.08 17:59:55 [Server] INFO Player instances are stored for efficiency.
09.08 17:59:55 [Server] INFO Loading WorldEdit v5.7-SNAPSHOT
09.08 17:59:55 [Server] INFO Loading HealthBar v1.8.2
09.08 17:59:55 [Server] INFO Loading SmokeTrail v8.1
09.08 17:59:55 [Server] INFO Loading mcjobs v3.1.8
09.08 17:59:55 [Server] INFO Loading Essentials v2.13.1
09.08 17:59:55 [Server] INFO Loading ClearLag v2.6.3
09.08 17:59:55 [Server] INFO Loading AutoMessage v2.3.5
09.08 17:59:55 [Server] INFO Loading MultiMOTD v1.2.2
09.08 17:59:55 [Server] INFO Loading WorldBorder v1.7.9
09.08 17:59:55 [Server] INFO Loading WorldGuard v5.9.1-SNAPSHOT
09.08 17:59:55 [Server] INFO Loading ProtocolLib v3.4.0
09.08 17:59:55 [Server] INFO Created default configuration.
09.08 17:59:55 [Server] WARN Version (MC: 1.7.10) has not yet been tested! Proceed with caution.
09.08 17:59:55 [Server] INFO Loading NoCheatPlus v3.13.7-RC-sMD5NET-b925
09.08 17:59:55 [Server] INFO onLoad: Early set up of static API, configuration, logging.
09.08 17:59:55 [Server] INFO Logging system initialized.
09.08 17:59:55 [Server] INFO Detected Minecraft version: 1.7.10
09.08 17:59:55 [Server] INFO Loading EssentialsChat v2.13.1
09.08 17:59:55 [Server] INFO Loading iConomy v7.0.4
09.08 17:59:55 [Server] INFO Loading PermissionsEx v1.22.10
09.08 17:59:55 [Server] WARN This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
09.08 17:59:55 [Server] INFO Loading CustomJoinItems v1.5.1
09.08 17:59:55 [Server] INFO Loading MineResetLite v0.3.6
09.08 17:59:55 [Server] INFO Loading Vault v1.5.6-b49
09.08 17:59:55 [Server] INFO Loading UralClans v1.0
09.08 17:59:55 [Server] INFO Loading ChatManager v1.19.1
09.08 17:59:55 [Server] INFO Loading EssentialsSpawn v2.13.1
09.08 17:59:55 [Server] INFO Loading WGFix vb.xd
09.08 17:59:55 [Server] INFO Loading AuthMe v3.3.6
09.08 17:59:55 [Server] INFO Loading ClearWorld v0.4c
09.08 17:59:56 [Multicraft] Skipped 89 lines due to rate limit (30/s)
09.08 17:59:56 [Server] INFO -------- World Settings For [world_the_end] --------
09.08 17:59:56 [Server] INFO Nerfing mobs spawned from spawners: false
09.08 17:59:56 [Server] INFO Mob Spawn Range: 4
09.08 17:59:56 [Server] INFO Anti X-Ray: true
09.08 17:59:56 [Server] INFO Engine Mode: 2
09.08 17:59:56 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
09.08 17:59:56 [Server] INFO Replace Blocks: [1, 5]
09.08 17:59:56 [Server] INFO Cactus Growth Modifier: 100%
09.08 17:59:56 [Server] INFO Cane Growth Modifier: 100%
09.08 17:59:56 [Server] INFO Melon Growth Modifier: 100%
09.08 17:59:56 [Server] INFO Mushroom Growth Modifier: 100%
09.08 17:59:56 [Server] INFO Pumpkin Growth Modifier: 100%
09.08 17:59:56 [Server] INFO Sapling Growth Modifier: 100%
09.08 17:59:56 [Server] INFO Wheat Growth Modifier: 100%
09.08 17:59:56 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
09.08 17:59:56 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
09.08 17:59:56 [Server] INFO Alternative Hopper Ticking: false
09.08 17:59:56 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
09.08 17:59:56 [Server] INFO Random Lighting Updates: false
09.08 17:59:56 [Server] INFO Structure Info Saving: true
09.08 17:59:56 [Server] INFO Sending up to 5 chunks per packet
09.08 17:59:56 [Server] INFO Max Entity Collisions: 8
09.08 17:59:56 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
09.08 17:59:56 [Server] INFO Max TNT Explosions: 100
09.08 17:59:56 [Server] INFO View Distance: 10
09.08 17:59:56 [Server] INFO Chunks to Grow per Tick: 650
09.08 17:59:56 [Server] INFO Clear tick list: false
09.08 17:59:56 [Server] INFO Experience Merge Radius: 3.0
09.08 17:59:56 [Server] INFO Item Despawn Rate: 6000
09.08 17:59:56 [Server] INFO Item Merge Radius: 2.5
09.08 17:59:57 [Multicraft] Skipped 4 lines due to rate limit (30/s)
09.08 17:59:57 [Server] INFO Preparing spawn area: 46%
09.08 17:59:57 [Server] INFO Preparing start region for level 1 (Seed: -7635331960013072580)
09.08 17:59:58 [Server] INFO Preparing start region for level 2 (Seed: -7635331960013072580)
09.08 17:59:58 [Server] INFO Enabling WorldEdit v5.7-SNAPSHOT
09.08 17:59:58 [Server] INFO WEPIF: Using the Bukkit Permissions API.
09.08 17:59:58 [Server] INFO Enabling HealthBar v1.8.2
09.08 17:59:58 [Server] INFO Enabling SmokeTrail v8.1
09.08 17:59:58 [Server] INFO is now enabled!
09.08 17:59:58 [Server] WARN Could not save config.yml to plugins/SmokeTrail/config.yml because config.yml already exists.
09.08 17:59:58 [Server] INFO Smoke Trail Metrics loaded
09.08 17:59:58 [Server] INFO Enabling mcjobs v3.1.8
09.08 17:59:58 [Server] INFO Using builtin logging methods.
09.08 17:59:58 [Server] INFO WorldGuard found.  Enabling WorldGuard protections.
09.08 17:59:58 [Server] INFO Found Vault 1.5.6-b49
09.08 17:59:59 [Server] INFO LOADED JOBS: землекоп шахтер строитель плотник охотник лесоруб фермер инструментальщик оружейник бронник рыбак повар алхимик чародей волшебник фокусник 
09.08 17:59:59 [Server] INFO max_jobs corrupted.  No default value found.  Setting default to 3!
09.08 17:59:59 [Server] INFO MC Jobs has been enabled!
09.08 17:59:59 [Server] INFO Enabling Essentials v2.13.1
09.08 17:59:59 [Server] INFO Версия Bukkit-ядра изменена. Версия не проверяется.
09.08 17:59:59 [Server] INFO git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10)
09.08 17:59:59 [Server] INFO 1.7.10-R0.1-SNAPSHOT
09.08 17:59:59 [Server] INFO [Vault][Economy] Essentials Economy hooked.
09.08 17:59:59 [Server] INFO Essentials: Using config file enhanced permissions.
09.08 17:59:59 [Server] INFO Permissions listed in as player-commands will be given to all users.
09.08 17:59:59 [Server] INFO Payment method found (Vault - Economy: iConomy  version: 1.5.6-b49)
09.08 17:59:59 [Server] INFO Enabling ClearLag v2.6.3
09.08 17:59:59 [Server] WARN --=[> This build was made for CraftBukkit 1.7.8 <]=---
09.08 17:59:59 [Server] WARN The following features have been disabled: mob-range
09.08 17:59:59 [Server] INFO No config updates found...
09.08 17:59:59 [Server] INFO Clearlag has been enabled!
09.08 17:59:59 [Server] INFO Enabling AutoMessage v2.3.5
09.08 17:59:59 [Server] INFO Enabling MultiMOTD v1.2.2
09.08 17:59:59 [Server] INFO Enabling WorldBorder v1.7.9
09.08 17:59:59 [Server] INFO [CONFIG] Using elliptic/round border, knockback of 3.0 blocks, and timer delay of 5.
09.08 17:59:59 [Server] INFO [CONFIG] Border-checking timed task started.
09.08 17:59:59 [Server] INFO For reference, the main world's spawn location is at X: 124.0 Y: 64.0 Z: 189.0
09.08 17:59:59 [Server] INFO Enabling WorldGuard v5.9.1-SNAPSHOT
09.08 17:59:59 [Server] INFO Blacklist loaded.
09.08 17:59:59 [Server] INFO (world) TNT ignition is PERMITTED.
09.08 17:59:59 [Server] INFO (world) Lighters are PERMITTED.
09.08 17:59:59 [Server] INFO (world) Lava fire is blocked.
09.08 17:59:59 [Server] INFO (world) All fire spread is disabled.
09.08 17:59:59 [Server] INFO Loaded configuration for world 'world'
09.08 17:59:59 [Server] INFO Blacklist loaded.
09.08 17:59:59 [Server] INFO (world_nether) TNT ignition is PERMITTED.
09.08 17:59:59 [Server] INFO (world_nether) Lighters are PERMITTED.
09.08 17:59:59 [Server] INFO (world_nether) Lava fire is blocked.
09.08 17:59:59 [Server] INFO (world_nether) All fire spread is disabled.
09.08 17:59:59 [Server] INFO Loaded configuration for world 'world_nether'
09.08 17:59:59 [Server] INFO Blacklist loaded.
09.08 17:59:59 [Server] INFO (world_the_end) TNT ignition is PERMITTED.
09.08 17:59:59 [Server] INFO (world_the_end) Lighters are PERMITTED.
09.08 17:59:59 [Server] INFO (world_the_end) Lava fire is blocked.
09.08 17:59:59 [Server] INFO (world_the_end) All fire spread is disabled.
09.08 17:59:59 [Server] INFO Loaded configuration for world 'world_the_end'
09.08 17:59:59 [Server] INFO 1 regions loaded for 'world'
09.08 17:59:59 [Server] INFO 0 regions loaded for 'world_nether'
09.08 17:59:59 [Server] INFO 0 regions loaded for 'world_the_end'
09.08 18:00:00 [Multicraft] Skipped 27 lines due to rate limit (30/s)
09.08 18:00:00 [Server] INFO Соединение с базой данных успешно установлено.
09.08 18:00:00 [Server] INFO База кланов загружена. (0)
09.08 18:00:00 [Server] INFO - База игроков загружена. (0)
09.08 18:00:00 [Server] INFO Плагин включен. (166 ms)
09.08 18:00:00 [Server] INFO Enabling ChatManager v1.19.1
09.08 18:00:00 [Server] INFO ChatManager enabled!
09.08 18:00:00 [Server] INFO Enabling EssentialsSpawn v2.13.1
09.08 18:00:00 [Server] INFO Enabling WGFix vb.xd
09.08 18:00:00 [Server] ERROR WGFix enabeled!
09.08 18:00:00 [Server] INFO Enabling AuthMe v3.3.6
09.08 18:00:00 [Server] INFO Loading Configuration File...
09.08 18:00:00 [Server] INFO Set Language: ru
09.08 18:00:00 [Server] INFO Vault plugin detected, hook with PermissionsEx system
09.08 18:00:00 [Server] INFO Hook with Essentials plugin
09.08 18:00:00 [Server] INFO Hook with EssentialsSpawn plugin
09.08 18:00:01 [Server] INFO AutoPurgeDatabase : 0 accounts removed.
09.08 18:00:01 [Server] INFO LICENSE : This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com
09.08 18:00:01 [Server] INFO Authme 3.3.6 enabled
09.08 18:00:01 [Server] INFO Enabling ClearWorld v0.4c
09.08 18:00:01 [Server] INFO Using WorldGuard!
09.08 18:00:01 [Server] INFO Enabled!
09.08 18:00:01 [Server] INFO Enabling ScoreboardStats v0.9.9
09.08 18:00:01 [Server] INFO Registered replacers: [PlayerPingVariable, BukkitGlobalVariables, GeneralVariables, VaultVariables, BukkitVariables]
09.08 18:00:01 [Server] INFO Enabling Marriage v1.11
09.08 18:00:01 [Server] ERROR Marriage is not compatible with the version of minecraft you are using!
09.08 18:00:01 [Server] ERROR Marriage kissing will be disabled!
09.08 18:00:01 [Server] INFO Hooked with iConomy 7 using Vault
09.08 18:00:01 [Server] INFO Enabling ColoredTags v2.1.1
09.08 18:00:01 [Server] INFO Hooked HealthBar plugin!
09.08 18:00:01 [Server] INFO Enabling ChestCommands v3.1.4
09.08 18:00:01 [Server] INFO Enabling ChatGuard v6.2
09.08 18:00:01 [Server] INFO ProtocolLib found! Hooking...
09.08 18:00:01 [Server] INFO AuthMe Reloaded hooked. Player will be checked after login.
09.08 18:00:01 [Server] INFO Loaded 690 words
09.08 18:00:01 [Server] INFO ChatGuard enabled!
09.08 18:00:01 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
09.08 18:00:01 [Server] Startup Done (5.977s)! For help, type "help" or "?"
09.08 18:00:02 [Server] INFO Added hook: AllViolations(NCP) [1.0].
09.08 18:00:02 [Server] INFO Post-enable running...
09.08 18:00:02 [Server] INFO Post-enable finished.
09.08 18:00:02 [Server] INFO Checking for Updates ... 
09.08 18:00:02 [Server] INFO No new version available
09.08 18:00:03 [Server] INFO The server administrator has disabled the updating system
09.08 18:00:11 [Server] INFO UUID of player enemycbc is 9fe49b3b-2da1-3926-83a9-85d8981cc70c

**Comment by games647** [comment]
It means that another plugin is overriding the sidebar scoreboard.

**Comment by RostislavCBC** [comment]
Thank for your help. I will be looking for plugin which overrids the sidebar scoreboard.

**Comment by games647** [comment]
Looks like I found the issue in #117
