### ISSUE TITLE
No Update on Top Kills

### ISSUE THREAD

**Issue by tobbepro1337** [games647/ScoreboardStats#113]
the Top Kills deos not update kills.
i got 15 kills but on the scoreboard it says i got 12
plz fix

**Comment by games647** [comment]
It updates it only on disconnect

**Comment by tobbepro1337** [comment]
ok but can you plz fix it so my players don't have to rejoin or is there any plugin that can do that for it

**Comment by games647** [comment]
>is there any plugin that can do that for it

I don't know one.

**Comment by tobbepro1337** [comment]
ok
