### ISSUE TITLE
Error when enabling Scoreboard

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#116]
When i reload the Scoreboard, or restart the server, this appears in the log:

http://hastebin.com/pegecomace.avrasm

**Comment by games647** [comment]
This is just for monitoring your server with VisualVM or Java Mission Control. If you don't use, you can just ignore it. 

The reason you get the stacktrace is that your hoster setted a security policy to their Java runtime which prevents to add data to the monitoring interface of Java.

**Comment by Eufranio** [comment]
But the Scoreboard isn't working here, that's the only log i get from ScoreboardStats :/

**Comment by games647** [comment]
Then you will have another error or it's conflicting with another scoreboard plugin.

**Comment by Eufranio** [comment]
I don't have another Scoreboard plugin and i'm using TablistPrefix, would it causing the problem?

**Comment by games647** [comment]
Yes enable compatibility mode

**Comment by Eufranio** [comment]
It's enabled

**Comment by games647** [comment]
And install Protocollib

**Comment by Eufranio** [comment]
I have it too

**Comment by games647** [comment]
ScoreboardStats runs in passive mode then. You properly have another scoreboard plugin installed. This show up in the sidebar.

**Comment by Eufranio** [comment]
MyCommand has a scoreboard feature but i don't use it, could be causing the problem?

**Comment by games647** [comment]
Yes that could be. It uses the sidebar too.
