### ISSUE TITLE
sTablist - no scoreboard after rejoin.

### ISSUE THREAD

**Issue by Dimatert9** [games647/ScoreboardStats#117]
ScoreBoardStats scoreboard doesnt appear after rejoin.
Compiled from latest sourced.

**Comment by games647** [comment]
Activate compatibility mode and install ProtocolLib.

**Comment by Dimatert9** [comment]
I have protocolLib and compatibility mode is enabled

**Comment by Dimatert9** [comment]
https://youtu.be/lOrNwN4aBeU
