### ISSUE TITLE
Add variables for GriefPrevention

### ISSUE THREAD

**Issue by MineTheCube** [games647/ScoreboardStats#121]
Hi,

Could you add support for GriefPrevention ? I would need these variables:
- remaining_blocks: [api method](https://github.com/BigScary/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/PlayerData.java#L164)
- total_blocks: [example code](https://github.com/BigScary/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L2086)

And you could add these as well:
- accrued_claim_block using `PlayerData#getAccruedClaimBlocks()`
- bonus_claim_blocks using `PlayerData#getBonusClaimBlocks()`
- group_bonus_blocks using `DataStore#getGroupBonusBlocks(UUID)`

I think you can use these events to update the variables: [package events](https://github.com/BigScary/GriefPrevention/tree/master/src/me/ryanhamshire/GriefPrevention/events)

Thanks :)

**Comment by games647** [comment]
The last one isn't public.

**Comment by MineTheCube** [comment]
Thanks :)

And what about these ?
- remaining_blocks: [api method](https://github.com/BigScary/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/PlayerData.java#L164)
- total_blocks: [example code](https://github.com/BigScary/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L2086) (without getGroupBonusBlocks for now)

**Comment by MineTheCube** [comment]
I made a pull request here: #133
