### ISSUE TITLE
ASkyBlock variables

### ISSUE THREAD

**Issue by Creatif** [games647/ScoreboardStats#126]
Concerning ASkyBlock variables:

Could you add a variable that count how many times all challenges were made ?
In ASkyBlock, challenges could be made severals times ;)

like %challenge_total%

You can use this ASkyBlock method:
skyBlockAPI.getChallengeTimes(player.getUniqueId())

```
    /**
     * @param playerUUID
     * @return HashMap of all of the known challenges with a boolean marking
     *         them as complete (true) or incomplete (false). This is a copy of the challenges
     *         and changing this list will not affect the actual list.
     */
    public HashMap<String, Boolean> getChallengeStatus(UUID playerUUID) {
        return new HashMap<String, Boolean>(plugin.getPlayers().getChallengeStatus(playerUUID));
    }
    
    /**
     * @param playerUUID
     * @return HashMap of all of the known challenges and how many times each
     *         one has been completed. This is a copy of the challenges
     *         and changing this list will not affect the actual list.
     */
    public HashMap<String, Integer> getChallengeTimes(UUID playerUUID) {
        return new HashMap<String, Integer>(plugin.getPlayers().getChallengeTimes(playerUUID));
    }
```

Full ASkyBlock API: https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/ASkyBlockAPI.java

Thanks

**Comment by games647** [comment]
Scoreboard already includes a variable for incomplete, complete and total challenges

**Comment by Creatif** [comment]
yeah I know it x). But a challenge could be made severals time.

As leaderheads propose:
asb-challenges: shows the players with the most finished finished challenges

asb-unique: shows the players with the most unique challenges finished

actually, asb-unique = %challenge%

Idk if i'm clear :s
