### ISSUE TITLE
MySQL Syntax error

### ISSUE THREAD

**Issue by Pdani001** [games647/ScoreboardStats#129]
This error shows up for me on plugin startup:
http://pastebin.com/CQYPU56n

**Comment by games647** [comment]
Try it without a reload

**Comment by games647** [comment]
I need your password-removed sql.yml

**Comment by Pdani001** [comment]
"SQL-Settings:
Username: ackills1
Password: ************************
Isolation: SERIALIZABLE
Driver: com.mysql.jdbc.Driver
Url: jdbc:mysql://db4free.net:3306/ackills1
Timeout: 1000
uuidUse: false"

**Comment by games647** [comment]
Please use haste/pastebin or gists.

**Comment by Pdani001** [comment]
http://pastebin.com/6g3TzXPU

**Comment by games647** [comment]
What version do you use? I don't find the line 196 in the latest version.

**Comment by Pdani001** [comment]
I use 0.8.3, but i got this problem every version above it.

**Comment by games647** [comment]
It cannot find your sql config. That's why it tries to invoke SQLite everytime.

**Comment by Pdani001** [comment]
It's right there: https://gyazo.com/8bc02acbd3248a62b10bf47ce3202ee0

**Comment by games647** [comment]
But it cannot parse it. Correctly, because it tries to setup a SQLite database.

**Comment by Pdani001** [comment]
Now i have a new problem.

**Comment by Pdani001** [comment]
When i try to change the mysql server it always use the last server.

**Comment by games647** [comment]
Try it without a reload

**Comment by Pdani001** [comment]
It's working now Thank You!
