### ISSUE TITLE
[BUGS]Cannot register replacer, PlaceholderAPI error and reload error

### ISSUE THREAD

**Issue by DeathrushW** [games647/ScoreboardStats#134]
When plugin starts, have this error
http://hastebin.com/kaqituloki.txt

When i reload it:
http://hastebin.com/ojunuhudaz.txt

And PlaceHolderAPI not working for me

**Comment by games647** [comment]
What's your SimpleClans version?

**Comment by DeathrushW** [comment]
Legacy, i will try update simpleclans
