### ISSUE TITLE
BungeeCord Variables errors 0.9.14

### ISSUE THREAD

**Issue by i9hdkill** [games647/ScoreboardStats#142]
Hi,
we are not using them, but still we are getting error messages likes this:
http://pastebin.com/SCjZP2f2

Worked fine with 0.9.12

**Comment by games647** [comment]
What's your BungeeCord version?

**Comment by i9hdkill** [comment]
We are using our own fork:
https://github.com/HexagonMC/BungeeCord
Only change is the readded 1.7 support

**Comment by games647** [comment]
What bungeecord plugins do you use? I assume another plugin is using the BungeeCord protocol incorrect.

**Comment by Eufranio** [comment]
My Bungeecord plugins: http://prntscr.com/dc1u0n

**Comment by Eufranio** [comment]
Do you recommend use an other Scoreboard plugin or wait for a fix?

**Comment by games647** [comment]
What variables do you use?

**Comment by Eufranio** [comment]
TPS, money, deaths and ping...
