### ISSUE TITLE
java.lang.NoSuchFieldException: annotations

### ISSUE THREAD

**Issue by TheChampTF** [games647/ScoreboardStats#143]
Hey

For some reason latest update is giving me http://paste.yu8.me/?73fc1f841aaff74a#5FR/yhhgwvjub/giOKqVNxIIFEigVtIr8bmF66JYeOY=

**Comment by TheChampTF** [comment]
@games647 So error on my part or fix being release? As this is unclear for me.

**Comment by games647** [comment]
Fixed in https://github.com/games647/ScoreboardStats/commit/e8cb5a2767666cac81ac6fd5f757afb86b22d785

**Comment by TheChampTF** [comment]
Pardon, this is still a problem on v0.9.14

**Comment by games647** [comment]
It's fixed after that release. In the mentioned commit.

**Comment by AngellitoX** [comment]
Excuse me, What's the link to download fixed releases? Or how can we obtain in?

Sorry if my question causes any disturbances.

**Comment by games647** [comment]
It's now uploaded. I was too busy earlier.

**Comment by AngellitoX** [comment]
Sorry for disturbing again, just saw you updated something on your mods.curse.com plugin website, but I can't see anything new. Does it take a while to show up your new file release?

In advance thank you so much, you've done a wonderful plugin.

**Comment by games647** [comment]
Bukkit has to approve it first.
