### ISSUE TITLE
Variables for NovaGuilds

### ISSUE THREAD

**Issue by MarcinWieczorek** [games647/ScoreboardStats#144]
Hello
I have implemented variables for my plugin, but I can see you prefer adding variables to your plugin. It would make mine more lightweight.

https://github.com/MarcinWieczorek/NovaGuilds/commit/62ed4240d706ad2da958b9b7852a31c6642bd05c

**Comment by games647** [comment]
>but I can see you prefer adding variables to your plugin

No I don't, it's better if it's implemented in your plugins. But I could add it to the Variables page on devBukkit if you want to.

**Comment by MarcinWieczorek** [comment]
Would be great! Thanks.
