### ISSUE TITLE
Error at startup, but plugin seems to work

### ISSUE THREAD

**Issue by KatsuroKurosaki** [games647/ScoreboardStats#147]
Good morning!

I have updated ScoreboardStats today (from 0.9.9 to 0.9.14) and when the server starts, this error message is shown, although I can see the scoreboard correctly. I am using the latest 1.10.2 Spigot build via BuildTools.
Let me know any further information you need. Thanks!

http://pastebin.com/9Xvw4ntN

**Comment by games647** [comment]
Duplicate #143
