### ISSUE TITLE
generated an exception

### ISSUE THREAD

**Issue by TheChampTF** [games647/ScoreboardStats#150]
http://paste.yu8.me/?2570a5367ef92645#YVQetvkv1HADR9UIz8fEpC4dMVGvtM3vAMxHEx1sDHU=

**Comment by TheChampTF** [comment]
Samme issue as http://paste.yu8.me/?b82faa9c288de2cb#+KydO/bQTILB5QumkFSCj96qhwmNRy2iICs9X0101NQ= and might be releated to http://paste.yu8.me/?3dfba28acb3afcee#GrSlY64didXqUHZ9P9IJun1xvMlQ0sgexeInvXjRpKI=

**Comment by games647** [comment]
Already fixed
