### ISSUE TITLE
The kills and Deaths not working

### ISSUE THREAD

**Issue by aBo0oDGamer** [games647/ScoreboardStats#154]
I want to use this plugin for my new game skypvp and i want scoreboardstats to show the players kills and deaths count but the plugin not work with the kills and deaths wen i want to use it and kill my self the deaths up from 0 to 3 how! and the kills from 0 to 5 and wen i reload the plugin back to 0
can please help me?
and sorry for my bad english D:

**Comment by games647** [comment]
Don't rely on reloads.

**Comment by aBo0oDGamer** [comment]
Ok but wen i put the plugin in the plugins file then start the server then add kills and deaths then reload the plugin show me the scoreboard changed then i test the deaths /kill aBo0oDGamer the death up from 0 to 2 whay and if i stop the server then start it again do the same thing

**Comment by aBo0oDGamer** [comment]
From 0 to 2 way **

**Comment by aBo0oDGamer** [comment]
Way? xD
From 0 to 2 why ***** :D

**Comment by aBo0oDGamer** [comment]
I'm using the v0.9.16 version for 1.8 spigot is the problem for that reason?

**Comment by Dimatert9** [comment]
0.9.15  work good

**Comment by aBo0oDGamer** [comment]
Sorry I'm using 0.9.15 but i test 0.9.16 it's work good but there is a problem D:
Wen i stop the server and i have in the board for example 10 kills wen i run it again the kills back to 0 why D:

**Comment by aBo0oDGamer** [comment]
Hello!
Can anyone help me?
I want the plugin please
