### ISSUE TITLE
No Mgr found for [] class java.util.ArrayList

### ISSUE THREAD

**Issue by Dimatert9** [games647/ScoreboardStats#155]
http://pastebin.com/u4snshpD

**Comment by Dimatert9** [comment]
http://pastebin.com/CuYA1Ebg
latest version from github

**Comment by Dimatert9** [comment]
Get this error when enable pvp stats

**Comment by Dimatert9** [comment]
#156

**Comment by Dimatert9** [comment]
not fixed in latest source @games647

**Comment by games647** [comment]
I never said it is.

**Comment by Dimatert9** [comment]
Why dont fix it?
In version 9.15 all good. In 9.16 i get this error and plugin dont work. Spigot 1.11

http://pastebin.com/AYSqpnyf full log
https://github.com/Dimatert9/Server1.8-1.10/blob/master/plugins/ScoreboardStats/config.yml config

**Comment by zerafox** [comment]
I too am getting this spam error, however I do not have pvpstats enabled at all.
