### ISSUE TITLE
Askyblock island level variable not working

### ISSUE THREAD

**Issue by YellowZaki** [games647/ScoreboardStats#157]
@games647 %island-level% is not working, it shows: -1.
I'm using 0.9.15 because in 0.9.16 anything work (no scoreboard is shown)
Thanks

**Comment by games647** [comment]
Do you have setup uSkyblock correctly?

**Comment by YellowZaki** [comment]
I'm using ASkyBlock (is it is indicated in the title)

**Comment by YellowZaki** [comment]
Now it is showing but it shows less levels than expected.
