### ISSUE TITLE
Any idea what this is in my console?

### ISSUE THREAD

**Issue by vashzx1** [games647/ScoreboardStats#158]
09.12 15:31:00 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
09.12 15:31:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_60]
09.12 15:31:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_60]
09.12 15:31:00 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_60]
09.12 15:31:00 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_60]
09.12 15:31:00 [Server] INFO at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_60]
09.12 15:31:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
09.12 15:31:00 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:230) ~[?:?]
09.12 15:31:00 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:155) ~[?:?]
09.12 15:31:00 [Server] INFO at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
09.12 15:31:00 [Server] INFO at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
09.12 15:31:00 [Server] INFO at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
09.12 15:31:00 [Server] INFO at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
09.12 15:31:00 [Server] INFO at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:357) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
09.12 15:31:00 [Server] INFO java.lang.RuntimeException: No Mgr found for [com.github.games647.scoreboardstats.pvpstats.PlayerStats@307dc177[id=0,uuid=3865a33b-84e7-48aa-a454-f4b3cf81d938,playername=LKPrime,kills=0,deaths=0,mobkills=0,killstreak=0,lastOnline=<null>], com.github.games647.scoreboardstats.pvpstats.PlayerStats@6e9ba07a[id=0,uuid=9566da02-1f2f-40be-978f-b67e10b7ca6b,playername=Usmcmech1987,kills=0,deaths=11,mobkills=0,killstreak=0,lastOnline=<null>]] class java.util.ArrayList
09.12 15:31:00 [Server] ERROR [ScoreboardStats] null

**Comment by games647** [comment]
Duplicate #155

**Comment by vashzx1** [comment]
Does that mean i have to disable pvp stats?

**Comment by games647** [comment]
or just downgrade
