### ISSUE TITLE
Failed to initialize pool: org.sqlite.Conn.isValid(I)Z

### ISSUE THREAD

**Issue by AlphaDelta9** [games647/ScoreboardStats#170]
compatibilityMode: true make scoreboard disappear
ProtocolLib version 4.2.1

v0.9.16: http://pastebin.com/QC9uqbeR
v0.10: http://pastebin.com/zjr2JqFW

**Comment by games647** [comment]
Which minecraft version do you have?

**Comment by AlphaDelta9** [comment]
1.10.2

**Comment by AlphaDelta9** [comment]
are this problem can solved on current version by temporary turn off pvpstats?
