### ISSUE TITLE
Enabling compatibility mode removes scoreboard

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#173]
No errors are showing in the console, but when I have it enabled, the scoreboard won't show up. After setting it to false (and remove ColoredTags), the scoreboard appears and fixes the issue...

**Comment by FunnyCraft** [comment]
also don't shows + , fix please

**Comment by Dimatert9** [comment]
yes. need fix

**Comment by Dimatert9** [comment]
@games647 
yes. need fix

**Comment by YellowZaki** [comment]
@games647 I confirm the issue, in previous versions it worked fine.

**Comment by Eufranio** [comment]
That took some time
