### ISSUE TITLE
Variable anomalies

### ISSUE THREAD

**Issue by SlimeDog** [games647/ScoreboardStats#174]
Environment: Spigot 1.11.2, ScoreboardStats 0.10.1, aSkyBlock 3.0.5.4 (all latest), and a long list of up-to-date plugins, sent via PM. Most variables report correctly, but some do not. If I need to configure differently, or If I am experiencing conflicts with other plugins, please identify, so I can take appropriate corrective action.

> exp 49848
xp_to_level 1201 or 940 or 7 in three different worlds
island 46

**aSkyBlock:is level** reports **/is level 15** :: verified detail with **/asadmin level <player>**
The value 46 is not stored anywhere that I can find. What interface is used to derive it?

**essentials:exp** reports **49,843 exp (level 122) and needs 470 more exp to level up.**
Experience is close, but why a difference? And why the wildly different values for level up?

**Comment by SlimeDog** [comment]
PlaceholderAPI + Expansion/ASkyBlock reports island level accurately.

**Comment by SlimeDog** [comment]
ScoreboardStats + PlaceholderAPI + Expansion/{Essentials,Player,Statistics,Vault}

- return the same value for money balance: PAPI %vault_eco_balance% = SS %money%
- return the same value for experience: PAPI %player_total_experience% = SS %exp%. PAPI %player_exp% = 0; not sure why that should be.
- return the same values for experience-to-level: PAPI %player_exp_to_level% = SS %xp_to_level%. That is, experience-to-level is different in the three tested worlds, as reported previously.

Any insight appreciated.

**Comment by games647** [comment]
>return the same value for experience: PAPI %player_total_experience% = SS %exp%. PAPI %player_exp% = 0; not sure why that should be.

A bug in the Bukkit API

>The value 46 is not stored anywhere that I can find. What interface is used to derive it?

This plugin uses the ASkyBlockAPI with the variable %island_level%

**Comment by SlimeDog** [comment]
Thanks. You might want to track that down, but I'll use the obvious workaround.
