### ISSUE TITLE
Add ThirdCurrency support

### ISSUE THREAD

**Issue by SliderKP** [games647/ScoreboardStats#179]
Please add variable to see in the scoreboard:

https://www.spigotmc.org/resources/thirdcurrency-bsp-adds-support-for-more-currencies.26273/

**Comment by games647** [comment]
It should already be covered by Vault.

**Comment by SliderKP** [comment]
hmm what is the variable to put in my config ? to show thirdcurrency? sorry for my ignorance

**Comment by games647** [comment]
%money%

**Comment by SliderKP** [comment]
i'm wrong with the request, sorry.!

I take it to congratulate you for the good plugin
