### ISSUE TITLE
Lack of thirst

### ISSUE THREAD

**Issue by SlimeDog** [games647/ScoreboardStats#184]
Long ago, I had %thirst% on my board. I just tried to add it again, but thirst reports the value -1 (after server reboot, since /sidebar reload does not always do the needful wrt changes in the variables list). My config.yml seems straightforward, but no joy. Spigot 1.11.2 and SS 0.10.1:
> compatibilityMode: false
> 
> disabled-worlds-whitelist: true
> 
> disabled-worlds:
>   - world
> 
> Scoreboard:
>   Title: '&8BlackDog Bonus'
>   Update-delay: 2
>   Items:
>     '&8points': '%money%'
>     '&8thirst': '%thirst%'

Any ideas why that doesn't work?

**Comment by SlimeDog** [comment]
Six more reboots, and it (magically) works. The file looks the same to me, although I cannot guarantee. :(

**Comment by SlimeDog** [comment]
A few more reboots, and I'm back to -1. No changes to configuration. :(

**Comment by SlimeDog** [comment]
Through all of this, _%money%_ has tracked consistently correctly. Any ideas?

**Comment by SlimeDog** [comment]
Is there any way to debug this on my test server?

**Comment by SlimeDog** [comment]
Is there anybody home?

**Comment by SlimeDog** [comment]
My suspicion is that, when it fails, ScoreboardStats is looking for variables before Thirst is loaded, so the latter cannot be found. Is that possible?

**Comment by SlimeDog** [comment]
Please make Thirst a soft dependency.

**Comment by games647** [comment]
If this is still relevant. This is something the author should fix.
