### ISSUE TITLE
ERROR WHEN STOP AND START SERVER OR RELOAD.

### ISSUE THREAD

**Issue by MiguelG2016** [games647/ScoreboardStats#185]
20.02 04:26:47 [Server] ERROR Could not load 'plugins/ScoreboardStats.jar' in folder 'plugins'
20.02 04:26:47 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
20.02 04:26:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[SPIGOT1.8.8:git-Spigot-db6de12-18fbb24]
20.02 04:26:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [SPIGOT1.8.8:git-Spigot-db6de12-18fbb24]
20.02 04:26:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [SPIGOT1.8.8:git-Spigot-db6de12-18fbb24]
20.02 04:26:47 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [SPIGOT1.8.8:git-Spigot-db6de12-18fbb24]
20.02 04:26:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [SPIGOT1.8.8:git-Spigot-db6de12-18fbb24]
20.02 04:26:47 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
20.02 04:26:47 [Server] INFO Caused by: java.util.zip.ZipException: error in opening zip file
20.02 04:26:47 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_73]
20.02 04:26:47 [Server] INFO at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_73]
20.02 04:26:47 [Server] INFO at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_73]
20.02 04:26:47 [Server] INFO at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_73]
20.02 04:26:47 [Server] INFO at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_73]
20.02 04:26:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[SPIGOT1.8.8:git-Spigot-db6de12-18fbb24]
20.02 04:26:47 [Server] INFO ... 5 more

**Comment by games647** [comment]
Corrupt jar please re download it.
