### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by krashing4** [games647/ScoreboardStats#189]
When i make the compatibilityMode: true the scoreboard stops working. I'm using spigot 1.8.8 with viaversion. can send log if needed

**Comment by Bodyash** [comment]
Same problem. In compability mode plugin using Protocollib

**Comment by YellowZaki** [comment]
Same here

**Comment by YellowZaki** [comment]
Bump!!

**Comment by flash8ack** [comment]
same on 1.11.2

**Comment by YellowZaki** [comment]
@games647 please, I cannot use any plugin which uses scoreboards...

**Comment by YellowZaki** [comment]
This was the commit which caused the problem: https://github.com/games647/ScoreboardStats/commit/b74a9ff217741cca0f7558c149b85488823ba71f
I've reverted back all the removed lines and now the plugin works with compatibilityMode=true

I also had to change the maximum characters of scoreboard to 32 on Settings.java when using the packets.

@games647

**Comment by flash8ack** [comment]
@YellowZaki Please give me your fixed version
