### ISSUE TITLE
Scoreboard Order

### ISSUE THREAD

**Issue by LuckyMonkyBaby** [games647/ScoreboardStats#190]
The scoreboard categories change place how do i fix that.

**Comment by YellowZaki** [comment]
It is not possible.

**Comment by SlimeDog** [comment]
The scoreboard is sorted by the values of the righthand column, largest at the top.

There are plenty of other scoreboard plugins that illustrate the way to control the order. Basically, the lefthand column must contain all the data, and the righthand column only integers that specify the order.
