### ISSUE TITLE
PLUGIN DONT WORK

### ISSUE THREAD

**Issue by FunnyCraft** [games647/ScoreboardStats#197]
When  compatibilityMode: true plugin dont work (version latest)

**Comment by games647** [comment]
Duplicate

**Comment by FunnyCraft** [comment]
You still do not fix compatibility!

**Comment by FunnyCraft** [comment]
My Plugins list  >> http://ssmaker.ru/01f42a81/

**Comment by BrainRTP** [comment]
"When compatibilityMode: true plugin dont work (version latest)"
👍
