### ISSUE TITLE
compatibilityMode does not work

### ISSUE THREAD

**Issue by FunnyCraft** [games647/ScoreboardStats#199]
![image](https://user-images.githubusercontent.com/14358233/27034450-6cccaff8-4f86-11e7-8213-81f35989450d.png)
![image](https://user-images.githubusercontent.com/14358233/27034465-7bc2a116-4f86-11e7-92eb-ae3910bd2f03.png)
When compatibilityMode = true, plugin does not display statistics

**Comment by Fonzee9** [comment]
Samething for me..

**Comment by NearDN** [comment]
Same here
