### ISSUE TITLE
ScoreboardStats not compatible with ASkyBlock

### ISSUE THREAD

**Issue by CCCCarsten** [games647/ScoreboardStats#200]
ASkyBlock: https://www.spigotmc.org/resources/askyblock.1220/

Error: 
18.06 15:53:31 [Server] WARN [ASkyBlock] "ASkyBlock v3.0.6.8" has registered a listener for com.wasteofplastic.askyblock.events.IslandLevelEvent on method "public void com.github.games647.scoreboardstats.variables.defaults.ASkyBlockVariables.onLevelUp(com.wasteofplastic.askyblock.events.IslandLevelEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Tastybento].

Auhor of ASkyBlock has informed you. But he says that there is as far no reaction from you.

**Comment by games647** [comment]
You're using an outdated ScoreboardStats version. Please update https://github.com/games647/ScoreboardStats/releases
