### ISSUE TITLE
Cannot use periods in the title section(Left side)

### ISSUE THREAD

**Issue by MrRiptide** [games647/ScoreboardStats#204]
For some reason, I cannot use a period in the left side, the logs states: "The variable play has to contain % at the beginning and one % on the end", but my text has no percent characters, only periods.  It is a tad annoying because I cannot put my server's IP into the scoreboard.  Any help or fix with this would be greatly appreciated.

**Comment by games647** [comment]
The left side only contains text and the right side only numbers. So you can only specify the ip on the left side and then you have to put a constant number to the right side.
