### ISSUE TITLE
Error inserting profiles

### ISSUE THREAD

**Issue by TheChampTF** [games647/ScoreboardStats#207]
Error inserting profiles on latest release of this plugin + spigot (also latest)

http://paste.yu8.me/?64b95337013e887f#2niXZyHWUyAwS5dkIPQ+Iio6jRNxx643bV7m5n+HuUg=

**Comment by games647** [comment]
Do you use SQLite or MySQL?

**Comment by TheChampTF** [comment]
SQLite

**Comment by games647** [comment]
Try to reset your sql config.

**Comment by TheChampTF** [comment]
No luck
