### ISSUE TITLE
Compability with Citizens

### ISSUE THREAD

**Issue by Evgeniy-xlv** [games647/ScoreboardStats#210]
Hello! I started use **ScoreboardStats** plugin today on my setuped server. But i have a problem in game. When plugin load, names of npc's will be the same as on the picture:
https://pp.userapi.com/c840225/v840225844/1c780/Kz1POdbzUhA.jpg

I don't know what to do, please help!

P.s Plugin for npc's - **Citizens**. I use russian words for npc's nicknames

**Comment by games647** [comment]
Looks like another plugin is setting those names. ScoreboardStats only changes the sidebar. I guess it's an incompatibility with an nametag plugin. You could try to enable compatibilityMode and install ProtocolLib.
