### ISSUE TITLE
FactionsUUID required in order to compile

### ISSUE THREAD

**Issue by RoboMWM** [games647/ScoreboardStats#212]
Not sure if adding `<optional>` in the pom was an attempt to not make it required for compiling, but it seems maven doesn't care and tries to find it anyways. Tried both `mvn clean install` and `mvn package`

https://hasteb.in/buyovekele.txt

**Comment by games647** [comment]
>Not sure if adding <optional> in the pom was an attempt to not make it required for compiling

It's for plugin developers. It prevents Maven from automatically downloading all dependencies of ScoreboardStats for projects that depends on ScoreboardStats. 

Currently the repository of drtshock [seems to be broken](https://github.com/drtshock/Factions/issues/858). I found no other maven repository that holds versions for FactionsUUID. So you would have to build and/or install the FactionsUUID project yourself to build ScoreboardStats.
