### ISSUE TITLE
Collision problem

### ISSUE THREAD

**Issue by Blamo27** [games647/ScoreboardStats#214]
Hello,

When I disable collision with the PaperSpigot configuration, the collision with other players is still active.
Tested with different version of ScoreBoardStats and 1.12 PaperSpigot

Configuration :
> enable-player-collisions: false
max-entity-collisions: 0
armor-stands-do-collision-entity-lookups: false / true

Can you help me ?

**Comment by games647** [comment]
You could try to enable compatibility mode

**Comment by Blamo27** [comment]
Yes it's working, thanks !
