### ISSUE TITLE
Please build latest version ScoreboardStats

### ISSUE THREAD

**Issue by Fiks75** [games647/ScoreboardStats#216]
Please build latest version ScoreboardStats with Fix ConcurrentModification for TopList (Fixes #215) for Spigot 1.12.2. I use Maven and NetBeans IDE, but I can not build.
Thanks.

**Comment by games647** [comment]
I made a new branch and backported the patch, because the new changes are likely to break with plugins using the old API.

https://github.com/games647/ScoreboardStats/releases/tag/temp-concurrent
