### ISSUE TITLE
mmsupernaturls plugin support

### ISSUE THREAD

**Issue by ChiefStroodle** [games647/ScoreboardStats#28]
can you please add support for the mmSupernaturals plugin.
Some variables:
[class]   - Shows the players current class
[power]   - Shows the players current power level out of the max power level
[witch]    - Shows if the player is on the WitchHunters kill list

Link to plugin: http://dev.bukkit.org/bukkit-plugins/mmsupernaturals/

**Comment by games647** [comment]
Project was deleted from Bukkit? Can I find it somewhere else?
