### ISSUE TITLE
Prison 2 compatibility

### ISSUE THREAD

**Issue by RayZz-** [games647/ScoreboardStats#41]
Can you add support for prison 2
here a link to the plugin :http://dev.bukkit.org/bukkit-plugins/mcprison/

**Comment by games647** [comment]
http://dev.bukkit.org/bukkit-plugins/mcprison/?comment=592
http://dev.bukkit.org/bukkit-plugins/mcprison/?comment=593
http://dev.bukkit.org/bukkit-plugins/mcprison/?comment=594

:disappointed:

**Comment by SirFaizdat** [comment]
I've decided that instead of letting go of the plugin, I will still update it for each new Minecraft version, and fix any critical bugs.
