### ISSUE TITLE
Mcmmo Power Level Tag and Health Bars

### ISSUE THREAD

**Issue by sbHango** [games647/ScoreboardStats#44]
After installing ScoreboardStats, mcmmo's power level tag below user's name/above the skin vanish in a few seconds after connecting and never appears again. Same thing happens with HealthBar for players

" mcmmo config Power_Level_Tags: true"

Any solution to this?

**Comment by madtomic** [comment]
If you are using the latest mcMMO. I recommend going back to a more stable build.

**Comment by games647** [comment]
Did you enabled compatibilityMode?

**Comment by sbHango** [comment]
@madtomic mcmmo runs fine for me, it's just that it's not compatible with scoreboard it seems.
@games647 how do i enable that?

**Comment by madtomic** [comment]
compatible mode : true in the config.yml

**Comment by madtomic** [comment]
I just read that you had HealthBar. Make sure show below name of turn off. You can't have both power level and player health at the same time.

**Comment by madtomic** [comment]
Player bar and after name needs to be false

**Comment by madtomic** [comment]
Unless you use the display style not using below name. This is shared with power level.

**Comment by sbHango** [comment]
Im using it on the same line as the name, not below. Is compatible mode on the scoreboard's config? I might be using an older version or something, how do i download latest one?

**Comment by madtomic** [comment]
http://dev.bukkit.org/bukkit-plugins/scoreboardstats/

**Comment by madtomic** [comment]
The latest version had compatiable mode on already. Anyway, to be safe. Just turn off below name.

**Comment by sbHango** [comment]
Okay, i made it to true. And when I join the server, the first 2 seconds i can see someone's power level, but then the scoreboard on the right appears and it vanishes

**Comment by sbHango** [comment]
and i completly removed healthbars

**Comment by games647** [comment]
Do you have ProtocolLib installed?

**Comment by sbHango** [comment]
I do not, is it required?

**Comment by madtomic** [comment]
Are you using the power level for anything? If not. Disable it in Mcmmo. That would not give you the glitch now. Scoreboard don't need the power level to be true to work.

**Comment by games647** [comment]
@sbHango yes

**Comment by madtomic** [comment]
You can have mcMMO, scoreboardstats, HealthBar all in the same server. Just make sure you have ProtocolLib

**Comment by sbHango** [comment]
Thank you! I might have missed that protocollib is required

**Comment by sbHango** [comment]
Another question, is it possible to disable scoreboard sorting from largest number to lowest? So if my config is
    '&aOnline': '%online%'
    '&bPower Level': '%powlvl%'
    '&6Money': '%money%'
    '&cMob kills': '%mob%'
    '&cKills': '%kills%'
    '&cDeaths': '%deaths%'
    '&cKDR': '%kdr%'
    '&cKillstreak': '%current_streak%'
it stays like that and is not sorted

**Comment by madtomic** [comment]
No, you can't not. Try make another issue to request this feature. I'd love this feature too.
