### ISSUE TITLE
PlayerPoints support

### ISSUE THREAD

**Issue by madtomic** [games647/ScoreboardStats#48]
Thought, I would ticket this to track it.

**Comment by games647** [comment]
^^

**Comment by madtomic** [comment]
YES!!!

**Comment by madtomic** [comment]
Did you remove faction support ? 😳

**Comment by games647** [comment]
No, I didn't. Why do you think so?

**Comment by madtomic** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6004542/6542035/d7953814-c4b9-11e4-8edd-801dd53d68e0.png)

**Comment by madtomic** [comment]
It minus out a lot in FactionVariables.java in latest commit.

**Comment by madtomic** [comment]
I just thought it was weird.

**Comment by games647** [comment]
Just moved it to another folder:

https://github.com/games647/ScoreboardStats/tree/master/src/main/java/com/github/games647/scoreboardstats/variables/defaults

**Comment by madtomic** [comment]
I see... 😁
