### ISSUE TITLE
API to create new scoreboards

### ISSUE THREAD

**Issue by LuisUrrutia** [games647/ScoreboardStats#52]
I'm a developer, and i'm trying to show my custom sidebar when someone is in the game, but i wanna restore the original scoreboard when he left the game. Actually i had the custom sidebar (scoreboard) but i can restore the original (with compatibility mode)
I tried in so many ways and nothing works.

This is what i have when a player left the game

```java
		scoreboardStats.getRefreshTask().remove(player);
		sbmanager.unregister(player);
		sbmanager.createScoreboard(player);
		scoreboardStats.getRefreshTask().addToQueue(player);
```

**Comment by games647** [comment]
How do you set your scoreboard?
Is it the main scoreboard?

Actually if you add offline players to the refreshtask they will be [ignored](https://github.com/games647/ScoreboardStats/blob/master/src/main/java/com/github/games647/scoreboardstats/RefreshTask.java#L50), because scoreboards shouldn't be saved in order to clean up after the plugin disables.

**Comment by LuisUrrutia** [comment]
Hi, well i solved it, my problem was this:
I'm making a plugin and i want to create a custom scoreboard for my game (btw should be an api for this, 'cause i do that by the hard way.. custom title, players name in the scoreboard, etc) and when they left the game, i want to restore the original scoreboard, and in order to do that i use this code:

```java
player.setScoreboard(Bukkit.getScoreboardManager().getNewScoreboard());
sbmanager.createScoreboard(player);
```

**Comment by games647** [comment]
Actually I'm working on an API. What do you expect from the it?

**Comment by LuisUrrutia** [comment]
well basically that we can create custom scoreboard easily, like set a custom title, and custom scores, i mean, in your plugin actually we can add custom fields and values to the scoreboard (if i'm not wrong) but we can't call a method to change the title, erase the content, and set/update custom fields/values... or create an object, maybe by Inheritance, to create a custom scoreboard. 
I'm not good with english.
