### ISSUE TITLE
it carrys over

### ISSUE THREAD

**Issue by doyouevnboss** [games647/ScoreboardStats#53]
okay so this is a awesome plugin and i love it but here is my problem. I am using multiverse and i only want the stats to show up in kitpvp. i also have a hub and surival. i have per world plugins and i have it set to only work on kit also throught the config itself its to be disabled in all words but kit. when u log in its fine and its not there if u go to survival its not there. the problem is if u go into kit it shows up like its supposed to but if you /hub it stays there, if u go to any other world after the one its enabled in it wont go away. i need it to go away after i leave kit! idk if u can fix that or if there is a way but please help!

**Comment by games647** [comment]
So, /hub teleports you to the hub world?

**Comment by doyouevnboss** [comment]
That is correct

**Comment by doyouevnboss** [comment]
Multiverse you can set up different worlds and run them all on the same server

**Comment by games647** [comment]
Do you have compatibilityMode activate?

**Comment by doyouevnboss** [comment]
what do you mean sorry im a first time server owner XD lol tell me what u need me to do or if u need config files or anything u need

**Comment by games647** [comment]
Yes, please post the config. That would helpful.

**Comment by doyouevnboss** [comment]
okay i will if it is at all possible would u like to log onto my minecraft server so i can show you? its a premium server

**Comment by games647** [comment]
I'm not on my PC, I'm on my phone.

**Comment by games647** [comment]
Could you please post your config of ScoreboardStats and the server address, so I could test it then?
