### ISSUE TITLE
could not compile

### ISSUE THREAD

**Issue by PhanaticD** [games647/ScoreboardStats#54]
Failed to execute goal on project scoreboardstats: Could not resolve dependencies for project com.github.games647:scoreboardstats:jar:0.9.2: Failed to collect dependencies for [org.bukkit:bukkit:jar:1.7.9-R0.2 (provided), com.comphenix.protocol:ProtocolLib:jar:3.6.2-SNAPSHOT (compile?), net.milkbowl.vault:VaultAPI:jar:1.5 (compile?), net.sacredlabyrinth.phaed.simpleclans:SimpleClans:jar:2.5.3 (compile?), org.black_ixx:PlayerPoints:jar:2.1.3 (compile), com.herocraftonline.heroes:Heroes:jar:1.5.5.4-SNAPSHOT (compile?), com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.01-SNAPSHOT (compile?), de.blablubbabc:insigns:jar:2.0 (system?), me.sirfaizdat.prison:Prison:jar:2.1.1 (system?), uSkyBlock:uSkyBlock:jar:2.1.0-SNAPSHOT (system?), com.massivecraft:Factions:jar:1.6.9.5-U0.1.15-SNAPSHOT (system?), com.massivecraft:factions-2.7:jar:2.7.1 (system?), com.massivecraft:mcore:jar:2.7.1 (system?), org.powermock:powermock-module-junit4:jar:1.6.2 (test), org.powermock:powermock-api-mockito:jar:1.6.2 (test)]: Failed to read artifact descriptor for com.herocraftonline.heroes:Heroes:jar:1.5.5.4-SNAPSHOT: Could not transfer artifact com.herocraftonline.heroes:Heroes:pom:1.5.5.4-SNAPSHOT from/to simpleclans-repo (http://repo.sacredlabyrinth.net/artifactory/plugins-release-local): Failed to transfer file: http://repo.sacredlabyrinth.net/artifactory/plugins-release-local/com/herocraftonline/heroes/Heroes/1.5.5.4-SNAPSHOT/Heroes-1.5.5.4-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]

**Comment by games647** [comment]
Which IDE do you have?

**Comment by PhanaticD** [comment]
netbeans, using clean and build. Also check the bukkit dev page I just need a working version basically

**Comment by games647** [comment]
Try to restart it. It looks like Netbeans couldn't get the the local artifacts too. It had this issue too.

**Comment by PhanaticD** [comment]
doesn't change anything

**Comment by games647** [comment]
Try to run it from the console

**Comment by PhanaticD** [comment]
i have not slept all night can I just get a jar

**Comment by games647** [comment]
I posted the link above

**Comment by PhanaticD** [comment]
oh thanks ill try from command line ater

**Comment by PhanaticD** [comment]
yeah same error from command line

**Comment by games647** [comment]
If you have time then, could you send me the complete log.

**Comment by games647** [comment]
I hope that fixes it. I have tested a lot and got the same issue after clearing my cache. It works now for me.

**Comment by PhanaticD** [comment]
just heads up the nixium build is failing now

**Comment by games647** [comment]
That's just a dns error. I hope it works after the next build

**Comment by PhanaticD** [comment]
Its been 20 minutes on the ci, does it normally take that long? I cant compile it on my computer either Failed to execute goal on project scoreboardstats: Could not resolve dependencies for project com.github.games647:scoreboardstats:jar:0.9.2: Could not transfer artifact com.comphenix.protocol:ProtocolLib:jar:3.6.2-20141129.134032-20 from/to shadowvolt-repo (http://ci.shadowvolt.com/plugin/repository/everything/): Connection to http://ci.shadowvolt.com refused: Connection timed out: connect -> [Help 1]

**Comment by games647** [comment]
No one of the repos timed out.

**Comment by games647** [comment]
I'll replace it temporarily
