### ISSUE TITLE
Stats are still glitched

### ISSUE THREAD

**Issue by PhanaticD** [games647/ScoreboardStats#55]
using build 35, http://phanaticmc.com/threads/the-kitpvp-stats-are-glitched.18234/

**Comment by games647** [comment]
What a silly typo https://github.com/games647/ScoreboardStats/blob/master/src/main/java/com/github/games647/scoreboardstats/pvpstats/StatsListener.java#L107 must be kills. I fix that now

**Comment by games647** [comment]
Should be fixed in: https://github.com/games647/ScoreboardStats/commit/3a345f86bab328dd6f78add675186e7df43ca7be
