### ISSUE TITLE
I just clone and build with maven and got errors.

### ISSUE THREAD

**Issue by madtomic** [games647/ScoreboardStats#56]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2015-04-23T10:46:32-04:00
[INFO] Final Memory: 10M/151M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project scoreboardstats: Could not resolve dep
endencies for project com.github.games647:scoreboardstats:jar:0.8.4: The followi
ng artifacts could not be resolved: net.milkbowl.vault:VaultAPI:jar:1.5, com.her
ocraftonline.heroes:Heroes:jar:1.5.5: Could not find artifact net.milkbowl.vault
:VaultAPI:jar:1.5 in comphenix-repo (http://repo.comphenix.net/content/groups/pu
blic) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

**Comment by games647** [comment]
Could you send me the complete log?

**Comment by madtomic** [comment]
http://pastebin.com/PGnvSFrq

Here it is. I just clone and did a maven install and build fail.

**Comment by games647** [comment]
>was cached in the local repository, resolution will not be reattempted until the update interval of
> comphenix-repo has elapsed or updates are forced

Try to rerun it with ```-U``` in order to force updates

**Comment by madtomic** [comment]
mvn -u clean install?

**Comment by games647** [comment]
yes

**Comment by madtomic** [comment]
It shows me options like if you type mvn 

It didn't do anything.

**Comment by games647** [comment]
It's case sensitive. (-U)

Sent from mobile

**Comment by madtomic** [comment]
It still failed.

http://pastebin.com/9KYLjvaK

I don't know what to do from here. >

**Comment by games647** [comment]
Do you have the correct version? It says scoreboardstats 0.8.4

**Comment by madtomic** [comment]
It has the recent source I would think. I just clone a fresh repo then try to build

**Comment by madtomic** [comment]
Maybe the Pom wasn't update ?

**Comment by games647** [comment]
Check the version in the pom. Is it 0.9.2?

**Comment by madtomic** [comment]
Yes it is. I can try a fresh repo clone later to test the build again.

**Comment by madtomic** [comment]
I deleted the old repo and fork the latest source again. I think it maybe resolve the issue. Thank you for looking at this.
