### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by austindkelly** [games647/ScoreboardStats#57]
I am not sure i have the correct permissions and im unable to tell exactly what the latest permission sets are so that i can enable and disable ss

I am using 

    - scoreboardstats.use
    - scoreboardstats.hide

in my default permissions group and i still get errors

i am going off permissions based on this - https://github.com/games647/ScoreboardStats/blob/master/src/main/resources/plugin.yml

Thanks

**Comment by games647** [comment]
Erros? Which ones?

scoreboardstats.use and scoreboardstats are assigned [by default](https://github.com/games647/ScoreboardStats/blob/master/src/main/resources/plugin.yml#L42)

In order to disable scoreboardstats with permissions, you need to give the user the negative permission.
