### ISSUE TITLE
PlacerholderAPI support

### ISSUE THREAD

**Issue by OldTownMC** [games647/ScoreboardStats#59]
Sorry, I wasn't able to find any other way to contact you, but it would be great to have a variable added:  https://www.spigotmc.org/resources/voteparty.987/ - Where it could display how many votes are required till a party occurs. (Can explain more if you don't understand what I mean after reading plugins functionality).

**Comment by games647** [comment]
Yes I'll implement it. Sorry for the delay.

**Comment by OldTownMC** [comment]
Could actually call this "Variables" now, found this: https://www.spigotmc.org/resources/placeholderapi.6245/ and https://www.spigotmc.org/resources/placeholderinjector.10022/ . Which I believe is potentially very useful.

**Comment by games647** [comment]
You can change the title too.

**Comment by games647** [comment]
Added support for the injector in the scoreboard branch
