### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by PhanaticD** [games647/ScoreboardStats#62]
http://pastebin.com/9ZQHYPWd

**Comment by games647** [comment]
Do have the libraries already downloaded? Then you could try to build offline by using:

"-o"

**Comment by PhanaticD** [comment]
nope :/

**Comment by games647** [comment]
Could you try it again. It works now for me. It seems one repository was and is up now.

**Comment by PhanaticD** [comment]
yes works
