### ISSUE TITLE
Scoreboardstats - Craftconomy

### ISSUE THREAD

**Issue by Lazorius** [games647/ScoreboardStats#67]
I have switched from Iconomy to Craftconomy, but now scoreboardstats doesnt show the money per-world, It shows the money somewhere else, I have craftconomy setup into 2 "pools", And scoreboardstats shows nether of them, It claims i own 100k, while i only own 1024 in one of the pools and 50 in the other

**Comment by games647** [comment]
Which Vault version do you use?

**Comment by games647** [comment]
Sorry for the delay.

**Comment by Lazorius** [comment]
i never got it to work, but i got the functionality needed with vault+ecomony+gringotts.

**Comment by games647** [comment]
Found out that this is actually a vault bug.
