### ISSUE TITLE
SkyWarsReloaded Variables

### ISSUE THREAD

**Issue by Someone-NEW** [games647/ScoreboardStats#69]
This is from my console and vanished no cound player on scoreboard not workind and ingame reload command not working fully so make compatible it to scoreboard from SkyWarsReloaded new one 

7.12 13:10:18 [Server] INFO SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
27.12 13:10:18 [Server] INFO DataSourcePool [ScoreboardStats] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
27.12 13:10:18 [Server] INFO Using [com.github.games647.scoreboardstats.pvpstats.PathReader] to read the searchable class path
27.12 13:10:18 [Server] ERROR ebean.properties not found
27.12 13:10:18 [Server] INFO Registered replacers: [PlayerPingVariable, BukkitGlobalVariables, GeneralVariables, BukkitVariables, VaultVariables]
27.12 13:10:18 [Server] INFO Enabling ScoreboardStats v0.9.1

**Comment by games647** [comment]
Why do you think it''s incompatible with the Skywards scoreboard?

**Comment by Someone-NEW** [comment]
now worl corectly i think and to be add a hiden player count fix and add some variables from SkyWarsReloaded will be helfull and maybe perworld scoreboard feature will be very cool and INGAME command for reload not fully reload and refresh to be reloaded. i use version spigot 1.8.8

**Comment by games647** [comment]
So this issue is about a hidden players and skywars variables.

**Comment by Someone-NEW** [comment]
Yes thats one of the issue error from console idk what the problem here is. About variables i a suggestion to be aded from SkyWarsReloaded and maybe fix that can be work with that plugin to.
I have scoreboard for SW enabled only on their world and when go back scoreboard not enabled again so not working.

**Comment by games647** [comment]
Which SkyWars version do you use? Can you send the link?

**Comment by Someone-NEW** [comment]
Now i use this one downloaded from here https://www.spigotmc.org/resources/skywarsreloaded.15464/history

**Comment by games647** [comment]
Plugin is no longer available
