### ISSUE TITLE
Color codes in v0.9.5

### ISSUE THREAD

**Issue by PabloMA98** [games647/ScoreboardStats#76]
This occurs with the default config.

![2016-02-13_15 12 39](https://cloud.githubusercontent.com/assets/11474413/13028081/650ca0e8-d264-11e5-85d5-89c4d360bd5f.png)

![fds](https://cloud.githubusercontent.com/assets/11474413/13028089/8be75780-d264-11e5-85e3-4648ef7a80f4.PNG)

**Comment by games647** [comment]
Thanks for the report.
