### ISSUE TITLE
A Skyblock Suggestion.

### ISSUE THREAD

**Issue by ryxan** [games647/ScoreboardStats#81]
https://www.spigotmc.org/resources/a-skyblock.1220/

Could the Variables for this be added. like island level?

Or will i have to move to uSkyblock..i would reeeeeally like to not have too do that. thanks

**Comment by games647** [comment]
>Or will i have to move to uSkyblock

No I'll add support for it when I have time.

**Comment by ryxan** [comment]
awesome. :+1:
