### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by Neverlookbackgrg** [games647/ScoreboardStats#84]
Today i tried merging the scoreboard stats with my sql via php my admin so i correctly put info into the config.The plugin generate the table into mysql in phpmyadmin.And it won't send any data into that.Every time i restart the server everyone starting from square 1

**Comment by games647** [comment]
Any errors at server startup?

**Comment by Neverlookbackgrg** [comment]
none there is only the sql script of scoreboard stats that says it will create the table if not exists

**Comment by games647** [comment]
But you didn't reloaded the server right?

**Comment by Neverlookbackgrg** [comment]
restart completly tried reload everything it will create the table into the sql but it won't put names into it or stats

**Comment by games647** [comment]
But it worked with the old DB?

**Comment by Neverlookbackgrg** [comment]
OLD DB yes although i would like to send all the data to an sql and then show it on my website that means i need the info to get added automaticaly into the sql

**Comment by games647** [comment]
Do you fixed it?
