### ISSUE TITLE
Colored Name Tags and Tablist Colors?

### ISSUE THREAD

**Issue by Xzeajan** [games647/ScoreboardStats#91]
I was using the scoreboard to have colors in my displayname floating above my head, and in the tablist, but since I am using scoreboardstats I dont have the colors anymore?

Is this an error or do you have any way to repair this?

I did already try to recreate the teams and reset the colors. No results. Still white names

**Comment by games647** [comment]
Activate compatibility mode and install ProtocolLib if you don't have it. It's actually a minecraft issue, but I worked around this.

**Comment by Xzeajan** [comment]
Installed and activated. Restarted server. Fixed it! Thanks alot!

**Comment by games647** [comment]
no problem
