### ISSUE TITLE
The method getUniqueId is not supported for temporary players.

### ISSUE THREAD

**Issue by FunnyCraft** [games647/ScoreboardStats#92]
http://pastebin.com/W1WBEBJW

**Comment by games647** [comment]
Plugin list please.

**Comment by FunnyCraft** [comment]
24.04 12:38:46 [Server] INFO Plugins (62): JoinCommands, FunnyCasino, ChatGame, EliteWeapons, CheatItemWatchDog, DynPad, FunnyCr, TickOptimizer, RandomPlacer, FunnyCase, NoteBlockAPI, PotionFix, RedstonePower, FunnyCraft, HideStream, UralChat, WorldEdit, HealthBar, SimpleElevator, Essentials, ClearLag, SwornGuns, AutoMessage, Chairs, WorldBorder, SunCraftHeads, Multiverse-Core, FunnyContracts, MRPvPMoney, PermissionsEx, SuperSpleef, Funnydone, MineResetLite, CustomJoinItems, TopStatistics, Vault, UralClans, ProtocolSupport, DrugMeUp, DrinksCMD, Scavenger, Marriage, WorldGuard, ChestCommands, McMusic, EssentialsSpawn, ChatManager, ShopGUIPlus, TitleManager, BowSpleef, mwParkour2, Jobs, LimitedWorldEdit, ProtocolLib, NoCheatPlus, PayDay, ColoredTags, WGLW, AuthMe, Passport, ScoreboardStats, ShoppingCartReloaded

**Comment by FunnyCraft** [comment]
http://pastebin.com/c5jCQDGB

**Comment by FunnyCraft** [comment]
please gather

**Comment by FunnyCraft** [comment]
you collect to collect the update?

**Comment by games647** [comment]
What?

**Comment by FunnyCraft** [comment]
Gather new build

**Comment by games647** [comment]
I think this some kind of plugin related, but yes I'll upload an update in a few days.

**Comment by FunnyCraft** [comment]
but you can collect the current build?

**Comment by games647** [comment]
The last version of this plugin is already uploaded.

**Comment by FunnyCraft** [comment]
where can I download?

**Comment by games647** [comment]
It's the one on BukkitDev, but there is this bug not fixed.

**Comment by FunnyCraft** [comment]
So I need a fixes.

**Comment by FunnyCraft** [comment]
Gather with fixed

**Comment by FunnyCraft** [comment]
Please.
