### ISSUE TITLE
NovaGuilds as 'compatibilityMode' plugin

### ISSUE THREAD

**Issue by MarcinWieczorek** [games647/ScoreboardStats#95]
My plugin does not work without compatibilityMode enabled. Please add 'NovaGuilds' to the code in order to inform users.

```java
//These plugins won't work without compatibilityMode, but do with it, so suggest it
String[] plugins = {"HealthBar", "ColoredTags", "McCombatLevel", "Ghost_Player", "TablistPrefix"
         ,"ColoredPlayerNames", "PingTest"};
```

More information:
https://github.com/MarcinWieczorek/NovaGuilds

**Comment by games647** [comment]
Does the plugin use scoreboard sidebar?

**Comment by MarcinWieczorek** [comment]
Not the sidebar. Only prefix and a scoreboard below player name, but my scoreboards dissappear a second after login when compatibility mode is off.

**Comment by games647** [comment]
Ok, I'll add it to the suggestion list.

**Comment by MarcinWieczorek** [comment]
Thanks
