### ISSUE TITLE
Flood + Incompatibility with TablistPrefix

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#98]
When running ScoreboardStats + TablistPrefix, the TablistPrefix stop working and the names still white. When i reload TablistPrefix, the names show correct but the Scoreboard disappear. 
When i tried put compatibilityMode: false to true and reload ScoreboardStats and load TablistPrefix, didn't work and i got this flood:
https://cdn.discordapp.com/attachments/185387567351332864/191207711210340354/unknown.png

I want to use ScoreboardStats with TablistPrefix :/

**Comment by games647** [comment]
Try to restart the server and not to reload it.

**Comment by Eufranio** [comment]
Sorry, i was using a old version xD
