### ISSUE TITLE
The scoreboard doesn't showing.

### ISSUE THREAD

**Issue by RaptorFX** [games647/ScoreboardStats#99]
I turned on pvp stats  and after this   the scoreboard doesn't showing anymore.I tried /sidebar but nothing !

**Comment by games647** [comment]
What plugins do you have? I think another plugin is overriding the scoreboard.

**Comment by RaptorFX** [comment]
AntiJoinBot,AuthMe-5.2,AutoSaveWorld,Citizens,Clearlag,ColorMe,CoreProtect,CratesPlus,DisguiseCraft,Essentials[All],GroupManager,HolographicDisplays,NoCheatPlus,Residence,ScoreboardStats,SkinsRestorer,Tim,votifier,worldedit,worldguard.My server is on 1.8

**Comment by games647** [comment]
Any errors in the console?

**Comment by RaptorFX** [comment]
No

**Comment by games647** [comment]
Could I see the log please?
